commerce_payment.commerce_payment_gateway.plugin.gocardless:
  type: commerce_payment_gateway_configuration
  mapping:
    description:
      type: string
      label: 'Description'
    access_token:
      type: string
      label: 'Access token'
    webhook_secret:
      type: string
      label: 'Webhook secret'
